[build]
  command = "npm install --force && npm run build"
  publish = "dist"

[build.environment]
  NODE_VERSION = "20.19.0"
  NPM_FLAGS = "--force --legacy-peer-deps"
  NITRO_PRESET = "netlify"

[[redirects]]
  from = "/api/*"
  to = "/.netlify/functions/:splat"
  status = 200

[[headers]]
  for = "/*"
  [headers.values]
    X-Frame-Options = "DENY"
    X-XSS-Protection = "1; mode=block"
    X-Content-Type-Options = "nosniff"